### ISSUE TITLE
Right Stick not working (+Button remapping?)

### ISSUE THREAD

**Issue by ZX3000GT1** [VFansss/mgs2-v-s-fix#11]
The right stick is not working for some reason not working. Everything else is working fine, including triggers and vibration. Assistance will be appreciated.

And also, is there a way to remap the buttons like the original launcher? Being constrained to only 2 control setup is not applicable for me since i did finish the game using my own custom setup.

**Comment by VFansss** [comment]
It's the second time within few days that someone report me something not working with gamepad .
This time is really strange cause right stick is automatically detected by game, and my fix (and external work that interact with gamepad, Xinput plus) don't mess with it in any way.

What OS do you have? If Win10, it's the last update? Gamepad used?

Inside game folder there is padana.ini. It's content is equal to this?

    00  Rx  N
    01  Ry  N
    02  X   N
    03  Y   N

Also (but I really don't think it's that the problem cause) you can try the previous version of the fix, the 1.02. [Download it here](https://github.com/VFansss/mgs2-v-s-fix/releases/download/v1.02/MGS.V.s.Fix.v1.02.zip). 

Also try to start the game with admin rights.

About button remapping:

I messed with gamepad layout for enough time to understand this: these 2 button layout it's the only feasible that cover all normal and "special" action (Like weapon hold up/release, katana move ecc) at the same time.

Doing a button remapper would be VERY time consuming for me, and I'm pretty sure that only very few people would mess with it. Also, with poor results, cause I'm pretty sure that is impossible to do a 'better' job without having to use external tools.

You can always use the original launcher. It's renamed in "_MGS2SConfig.oldandcrappy" inside the game folder. Simply change it's extension to .exe (mantain the underscore, or otherwise V's launcher will rename it again the next time you start it).

Go to gamepad mapping and do what you like (Xinput plus libraries should even work here, so you can set triggers like gamepad button 11 and 12, if I remember correctly). 

When you have finished you should note padbtn.ini and padana.ini: those files contain gamepad settings for "normal mode"; first person mode in VR are memorized inside padbtns.ini and padanas.ini). Copy them in your desktop, launch V's fix, open settings, save (this all because original launcher overwrite graphical, vga and others settings) and put these 2 .ini back inside game folder and, obliviously, overwrite.

I don't think is time well spent, but you can always try something that fit better you gameplay style. These 2 layout are the only that allow all special action without requiring 7 fingers for hands. Expecially weapon hold up/release has severe problem. If you, from the original launcher, map your gamepad 1:1 to what original launcher tell to you, you will get a completely mess.

Let me know!

**Comment by ZX3000GT1** [comment]
Well, i opened padana.ini, and discovered this : 
`00  Rz  N
01  Z  N
02  X   N
03  Y   N`

Yup, Rz and Z were there instead of Rx, Ry. My game pad is not an official X360 Controller, rather it's the compatible one which has 2 modes, Xinput and Dinput. It seems that the ini file takes the RS axes from the Dinput mode, hence marked ad Rz, Z, and RS not working. Changing it to Rx, Ry makes the RS work and I become a happy man. Thanks!

As for the button remapping, i understand that most people wouldn't even care about it. But really, the only change i made was switching bumpers functions with triggers functions. I'll manage with the controls then.

Once again, thanks for the quick reply!
