### ISSUE TITLE
I can't run diagonally

### ISSUE THREAD

**Issue by muleet** [VFansss/mgs2-v-s-fix#16]
Hi, I'm playing with a 360 pad and i noticed a very annoying problem : each time I try to run diagonally the character stops to run, and starts to walk instead. I'm surprised no one seems to have the same problem.

I made a short gif to show how annoying it is. http://i.imgur.com/zZGRn7i.gifv In this gif, I was always pushing the stick to the max but while I push it precisly between the X and Y axis, Snake starts to walk. The game seem unable to understand that I should be able to push the stick to the max for X and Y axis at the same time.

I never had this kind of problem before, in any other game. Not even when I played MGS2 without the "V's fix patch" (which I installed only for the vibration of the pad, which was the only thing important to me that wasn't working, with the other patches I used in my previous installation of the game).

(I thought I could fix that by getting the source code of the patch, and by updating the "[XIpunt Plus](https://sites.google.com/site/0dd14lab/xinput-plus)" software to its last version, but... I don't know how to compile. I'm not sure at all it was really the problem too, anyway.)

Edit : So I realized, after reinstalling my OS (windows 7) and reinstalling the game with the patch + alchemy + a crack + xpadder, that my problem is still there. So your patch wasn't responsible for it. I guess you can't help me then. :/ Sorry for this thread. (It's very annoying because I would have liked to try to play in european extreme and to try to speedrun a little, but clearly I can't at all with this...)

**Comment by VFansss** [comment]
Before all: I'm really sorry for the long waiting response time!

I didn't had the game with me, and then my gamepad broke so I had to find another one!

I swear: it's hard to do a patch that work flawlessly on all configurations ; I've been really careful doing all things right, but sometimes things goes weird (like this case) and isn't easy to pinpoint the problem.

Honestly I don't think the problem is caused by the fix, but this doesn't mean that we can't try to find a solution!

The XInput Plus library I used is the last version, so updating it would be...useless. Like you told me the problem could be caused by a wrong deadzone offset. You can mess manually with some gamepad configuration downloading the Xinput Plus software **([HERE](https://sites.google.com/site/0dd14lab/xinput-plus),** than click the blue link on top). Unzip it somewhere, than start XInputPlus.exe. On the top right of the windows press 'SELECT' and open mgs2_sse.exe (the game executable). Answer yes on the next question. Then you can change a lot of gamepad option, including left stick sensibility ones.

I've also did an attempt to do it for you so, assuming that the 360 gamepad is original and fully working, you can try:

[XInputPlus.ini.gz](https://github.com/VFansss/mgs2-v-s-fix/files/1097251/XInputPlus.ini.gz)

You can open .gz files with WinRar or 7Zip. Github didn't allowed me to upload .zip files, don't know why :/ 

Use V's fix, select the gamepad layout you prefere, press SAVE and then paste the .ini file inside the archive into game directory. Answer 'yes' to file replacement.

If this doesn't change anything....we can try something different...

**Comment by muleet** [comment]
Thanks bro !
"Messing" a little with XInputPlus worked ! I just had to add a little deadzone. (I first tried your XInputPlus.ini but my sticks didn't worked anymore, only the dpad, that was a little strange. Maybe I didn't follow correctly what you said, I don't know.)
Thank you very much to take the time to help me, even though my problem didn't had any link with your great patch. I can go lose happily in the european extreme mode, now.

**Comment by VFansss** [comment]
I'm glad I've been helpful!

Have fun, mate! And good luck for the playthrough ❕

**Comment by berserkingyadis** [comment]
Im currently experiencing the same issue with my x360 Controller, diagonal running isnt working some of the time. Ive downloaded the XInputPlus GUI to configure my XInputPlus.ini, since it has a nice preview of the controller input/output depending on your settings.

![image](https://user-images.githubusercontent.com/9959527/57683985-235aac80-7635-11e9-9275-10dc97ea2b5c.png)

@muleet Can you elaborate what you mean with "adding a little deadzone" ?

**Comment by muleet** [comment]
On your screen have a data that is called "Dead Zone" and it is at 0% right now, so try to... increase it ? :p
The Dead Zone is the zone of your stick in which your computer won't be sensitive to the mouvements you'll do. It's been 2 years since I've done that change but if I recall correctly it was enough to fix that diagonal run issue. Try 20% or 30% maybe.

**Comment by berserkingyadis** [comment]
I figured as much, but I wasnt sure about how this would effect the "maximum" the stick can be since that is where it doesnt seem to be enough (walking, not running). I thought changing the Saturation to a lower value (what VFansss did I think in that ini they linked I think) would be the solution since that seemed to increase the radians of the output.

![image](https://user-images.githubusercontent.com/9959527/57692646-86553f00-7647-11e9-8535-91c8f00b3cc7.png)

It sadly didnt work.

I shall try increasing the deadzone percent as you suggested this evening when I have the time. Thanks for the fast answer!
