### ISSUE TITLE
Mouse and FPP VR

### ISSUE THREAD

**Issue by TheKrzysiek** [VFansss/mgs2-v-s-fix#17]
Is there any chance of adding mouse control or a different scheme for FPP VR missions to make them more comfortable?

**Comment by VFansss** [comment]
Could be done, yes...

All depend on what control scheme you want to achieve!

**Comment by TheKrzysiek** [comment]
Something like moving the attack/fire button from X on Xbox controller to maybe bumbers so you can move, aim and fire at the same time. Would make those missions a lot more comfrotable. Or, while using the keyboard, aiming with the mouse and shooting with mouse buttons, however I remember that in original you could only move camera with keyboard.

**Comment by VFansss** [comment]
Before all...sorry for the late reply. I didn't had the game with me, and only today I could try some experiments...

Now, let me explain: your idea of moving and shooting in first person isn't bad. I've tried to make something like and it work good...

Unfortunately the camera isn't good enough to make it smooth like a modern first person shooter (for example) because moving view with right stick add some kind of "acceleration" that I can't disable in any way, and the final result isn't exactly phenomenal. 

Another idea: using one hand for gamepad moving and the other for shooting with mouse, but then you couldn't press any other buttons. Also it's kinda odd... 

So there isn't any particular "amazing" way to handle this 😞

**Comment by TheKrzysiek** [comment]
Thanks for the info, I'll check it out as soon a I can :)

**Comment by geecko86** [comment]
Being precise and shooting Vamp with the sniper rifle is very hard with a 360 Controller. It keeps aiming just left of where I want to shoot.

Similar to what's being asked in this thread, is there any way your V fix could help with that?

**Comment by VFansss** [comment]
If you have an original xbox360 controller it should work good...

Maybe you can try to set a minor sensibility for your left stick, so you can aim with more precision.

The project use XInput Plus for restoring controller input

* so [DOWNLOAD IT](https://sites.google.com/site/0dd14lab/xinput-plus) pressing the blue link on the top

* extract it whatever you want

* open XInputPlus.exe, press the SELECT button on top right and select the main game executable (mgs2_sse.exe)

* Answer yes to the question that should appear.

Now all gamepad settings are loaded into the software. You can change it so make more comfortable for you. 

If you want to lower the sensibility, go to the "Sticks" tab and lower the "response" slider and "deadzone". You can test it in real time.

After you finished, just press APPLY, and start the game.

Be careful that if you press SAVE again from the option fix it will overwrite you setting.

Tell me if it works like you intended.

**Comment by VFansss** [comment]
Another button layout will be added in the last build of the fix to achieve a more "modern feel"
