### ISSUE TITLE
Switch from UAL to Simple DLL loader

### ISSUE THREAD

**Issue by Tomasak** [VFansss/mgs2-v-s-fix#22]
As title says. Here is gtaforums topic for it http://gtaforums.com/topic/894847-simple-dll-loader/
It's more convient since Widescreen fix for MGS is distributed as DLL, so you don't have to rename it to asi anymore.

**Comment by VFansss** [comment]
Seems very interesting. Isn't a top priority issues so I will keep it in mind for the next release (now I'm busy with another big project, so I can't focus on this!)

**Comment by VFansss** [comment]
Finally I've decided to...not do it.

Why?

Because Simple DLL Loader read loadable "libraries" from an external .ini file, while UAL simply run things that exist inside the 'scripts' folder.

To do the former thing I would have to create a dynamically "ini writer" builder that add paths, and be sure that would work correctly under any case. That would require a good (albeit not SO high) amount of time. 

With the latter I have only to extract a zip, without having to worry about anything.

I think that make things remain like they are its the best balance between time, thoughtless of code and functionality.

Also, I don't think there will be more extra release of the Widescreen Fix by nemesis2000, and that would make all that work completely...useless.

I hope that extra additions to the fix will make this "deficiency" more bearable 😄
