### ISSUE TITLE
USB gamepad not working

### ISSUE THREAD

**Issue by geomatt** [VFansss/mgs2-v-s-fix#23]
I've installed the game some days ago and I've always been playing well with my generic USB gamepad (ps2- like, with 2 analog sticks). I had some trouble with switching graphic card and some graphic glitches (I play on laptop with geforce), so I decided to try this Fix and everything is ok, very good job! No more graphic issues...
Unfortunately, after applying the fix,  the controls of my USB gamepad don't work properly and i can't find a way to re-map them. Before the fix, they were absolutely fine

Any suggestions?

**Comment by geomatt** [comment]
FIXED: tried to resotr the old MGS2SSET.ini and it works PERFECT!

**Comment by VFansss** [comment]
MGS2SSET.ini is used by the old game setupper.

Is never used by my fix, so its impossible that "restoring" it should fix anything.

Can you please explain better to me what you have done? Maybe I can understand something important!

**Comment by geomatt** [comment]
You're right, I've checked it out and the issue wasn't on that file actually. I was wrong. After a clean re-installation of both game and fix it's been working good.
Is there any option to setup buttons and triggers on my usb gamepad? I can't use the control "slow" when in game

**Comment by VFansss** [comment]
There are a lot of methods to achieve this.

The 2 available button layouts (V's and PS2) are already configurated for all in-game action.
The are working good with 360/One controller because driver reason.

If you emulate one of these 2 controller correctly you can achieve a perfect configurations without having to waste too much times (also you can play with others Win games that support 360 controllers).

Use x360 ce ([Check this video for reference](https://www.youtube.com/watch?v=zOcWS-WmoMM. What an ugly music, however) and you should achieve a 100% compatibility within minutes.

**Comment by geomatt** [comment]
tired to emulate the x360 controller. x360ce can see my gamepad and ive done every step showed in the video...but unfortunately once i start the game it says something's wrong with the hardware and it crashes. I also cannot save new settings from the fix setup

**Comment by VFansss** [comment]
Sorry for the late reply.

Tell me something: aside the "slow" button, all other buttons are working good?

The 4 action buttons, the trigger, the start and select buttons, the weapons/items button selector (L2,R2)?

If so, its already set and you don't need to change it: The slow button is used for release the weapon without shooting, and by default is set on Left Stick Button (L3).
