### ISSUE TITLE
Weapon raising/lowering

### ISSUE THREAD

**Issue by Creuwey** [VFansss/mgs2-v-s-fix#24]
Even though the current way to lower the weapon with L3 works, it's still really awkward to handle assault rifles. Is it possible to change it to something like this?

Click L3 to raise weapon and click again to lower. (AFAIK this is how XBOX/360 versions of the game handle this. Not sure if firing the weapon or leaving first person lowers the gun.)
or
Hold L3 to raise weapon, let go to lower.

This would make doing hold-ups and firing short bursts with assault rifles a lot more intuitive.

**Comment by VFansss** [comment]
> Is it possible to change it to something like this?

For reasons that I don't really understand...no: pistols and assault rifle are handled differently by the game.

If for the first ones you can simply press and release a button ( as you rightly said), for assault rifle isn't enough: is needed to press another button. And this stupid things is hardcoded into game logic.

I've handled this thing using L3 and RB ( if you use V's Layout), but without using an **external** tool isn't possible. 

I can try to investigate for changing it, but isn't exactly my main field so 🙄

**Comment by Creuwey** [comment]
All right.

I did some testing with V's layout and it works a lot better than the PS2 one, but I'm not really a fan of the control scheme as a whole. On the PS2 layout you can aim an assault rifle holding X and L3. When you want to shoot you let go of L3, but pressing and holding it again doesn't stop your gun from firing right away (there seems to be a slight delay with the action). Unlike in V's layout, where - while holding X - you can fire short bursts by letting go of RB and pressing it again. But yeah, (like you said) it only works with assault rifles.

I thought it would be as simple as binding light-press weapon button to L3, but I guess that doesn't really work. That "aim without firing" binding could be pretty useful on the PS2 layout too, but I'm not really sure where i'd put it without it interfering with other bindings.

**Comment by VFansss** [comment]
Sorry for the late reply!

You have done well your test! Unfortunatelly, you arrived to the same conclusion: it's impossible to do a "perfect" PS2 layout. Maybe using an external tool can be achieved, but I'm sure this would give some other problems...

After tons of time spent, I didn't found the cause of that "slight delay" you are talking about!

The V's Layout allow any ingame actions, and isn't so different from the original xbox game release.

In the future I can try to resolve this in some "creative way", but I don't have an immediate workaround, unless suggesting to use the V's Layout :/

**Comment by MrMirvC** [comment]
You may want to use SCP Server. It's a tool that lets you to use your PS3/4 controller as 360's ones. It's not like XPADDER or others. It's just Plug n Play. I use this software for the "Max PS's controller feedback" on emulators. I didn't test it on MGS2 tho because it is not in the right home.

This is the [video tutorial](https://www.youtube.com/watch?v=x_VzPpFHbCw)

**Comment by VFansss** [comment]
I can confirm that SCP Server is working, because it's the one I used until now with my Ps3 Sixaxis.

It's even noted into [my Wiki under the 'Supported controllers' chapter](https://github.com/VFansss/mgs2-v-s-fix/wiki/Controllers-&-Actions#supported-controllers)

Unfortunatelly, this issues is far beyond the simple gamepad compatibility: ps3 Sixaxis/Dualshock has analogic buttons, so TEORICALLY it's possible to create a button layout exclusive for ps3 controllers that support weapons hold up with a slighty pressure of the aim button.

But, pratically, this can't be done without an external tool because SCP Server (and all other software that mimic an original x360 button) because game doesn't allow "analogic" button pressing.

Because that, it REQUIRE to set 2 different buttons: one for aim, one to tell the game that you are aiming slowly.

So, this is a software issues that is almost impossible to patch.

It can be circumvented through external tools that does button macros, but it's kinda hard and, well, they require external tools.

Maybe in the next version, if I have the time, I can create a layout specifically for using analogic buttons on ps2 and ps3 gamepad (the only through history and time that phisically have analogic buttons).

**Comment by VFansss** [comment]
After all this time I didn't found ANY software that recognize the "analog input" from a DS3 (or a Sixaxis) controller.

I think I will give up on this.
