### ISSUE TITLE
[Silly question - Sorry about it] Cheats.

### ISSUE THREAD

**Issue by Lion4K** [VFansss/mgs2-v-s-fix#30]
@VFansss I'm sorry to open an Issue to ask this.

I was remembering how MGS1 for PC had those Launching Command Line Parameters like "MGSI.EXE -Cheatenable" and I was wondering if its possible for you to implement cheating on MGS2 following the same pattern or on the Fix Main menu itself or something like that.

Again, I'm terribly sorry to ask such silly question, but I couldn't contain myself.

**Comment by VFansss** [comment]
Don't worry, is not a silly idea: I had already thought about it in the past!

The V's fix is patching some value inside the game executable (the .exe), and the few hacks I've saw about mgs2 ( I saw them distractedly on youtube) does the same things: value patching through hex editing.

At least "infinite ammo" and "infinite health" could be done, and could be even integrated through the fix interface.

This would require a separated logic for cheats and could be definitively done, but would require quite a few time (I have to re-write a lot of things) and right now I didn't kinda have the right incentive to spend so much time on it!

**Comment by VFansss** [comment]
After more than 1 year, I can say that I finally implemented cheats (or at least they will be present from the next build of the fix!).

For now they are only 2 cheats, but they should be fun to play.

I will create a Wiki entry on how to activate them, because they are actually hidden from the fix.

Delivered 🎉
