### ISSUE TITLE
 dual graphics

### ISSUE THREAD

**Issue by yukiumi** [VFansss/mgs2-v-s-fix#34]
Because I am Japanese, English grammar may be wrong. 
I am sorry if it is  wrong.
objects are drawn to the double in movie.  please help me.

**Comment by VFansss** [comment]
Hi!

Can you please provide me a screenshot when the bug occour?

**Comment by yukiumi** [comment]
![metal gear solid 2 _ substance 2018_03_22 21_47_17](https://user-images.githubusercontent.com/37660788/37771391-cf4afef0-2e1a-11e8-88e9-8fa3ac79b791.png)
![metal gear solid 2 _ substance 2018_03_22 21_47_33](https://user-images.githubusercontent.com/37660788/37771398-d32b6b0e-2e1a-11e8-8f2b-87597e01a871.png)
 
These are some, but such things happen in most movies.

**Comment by VFansss** [comment]
Thanks!

There is an issue with the graphical adapter. I recognize that because in the first 3 screenshot the water is glitched in that strange 'grey' texture. I'm pretty sure that is the same things even during the gameplay, isn't it?

The V's fix does its best to patch the game to make it recognize all different VGA adapters that the user could have, but can fail in some (untested) cases...

Are you playing on a laptop? (=not a desktop pc). If yes, you can try to enable the "Laptop mode" from the 'Resolution tab' of the fix. Check the [number 5 option showed in THIS screenshot](https://github.com/VFansss/mgs2-v-s-fix/wiki/images/Tab_Resolution.PNG).

Also can you please provide me the graphical adapters name that are showed [near the option labeled in 6 in this screenshot?](https://github.com/VFansss/mgs2-v-s-fix/wiki/Settings-Menu#resolution-tab)

**Comment by yukiumi** [comment]
Thank you for your reply.　i play in desktop pc.  graphical adapters is GTX650.

**Comment by VFansss** [comment]
So, on Graphics Adapter, is ONLY showing "GTX650" without any other characters/string?

If so that's why isn't working: the V's Fix isn't recognizing that your VGA is an NVIDIA.

Because that the game is running without any optimization for NVIDIA, thus making these graphical glitches...

To fix that I should release another version of the fix :(

Until then, you can try [THIS](https://drive.google.com/open?id=1mKgV204_z2z-f3PBm7vMBkdhXr91JoQh) to see if the things is solving. Set your game through the V's Fix, press "SAVE" and then extract the content of that .zip inside the "/bin" folder, overwriting the file.

Please tell me if its working :)

**Comment by yukiumi** [comment]
yes only gtx650 only

**Comment by yukiumi** [comment]
its working . thanks

**Comment by yukiumi** [comment]
However, it still draws twice.

**Comment by VFansss** [comment]
I honestly think that this is an issue with your configuration/PC instead of there being a problem of the fix.

What snake tales is crashing, and when?

**Comment by VFansss** [comment]
This is almost impossible I think, and [THIS is a pratical dimostration that](https://www.google.com/search?q=gtx+650+gpu-z&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwj22vawr-TaAhVKvhQKHQqGBNAQ_AUICigB&biw=1366&bih=619#imgrc=OiWz3CmKbmXPFM:) that a GTX650 should have the "NVidia" string inside the name.

Honestly I think it a fake VGA or something. Or maybe I'm only a fool, who know.

But last build of the fix will recognize an NVidia card even if it hasn't "Nvidia" inside the card name, so at least this can be corrected!
