### ISSUE TITLE
"Failed to create IDirectSound8 Object" when using DS4 audio jack

### ISSUE THREAD

**Issue by Jvolt7** [VFansss/mgs2-v-s-fix#47]
I connected my DS4 through USB and set the Wireless Controller audio device as the main audio device, when starting the game I noticed that it gave me the "Failed to create IDrectSound8 Object" and then it closes , but if I switched it to the main audio device the game would boot normaly even with the DS4 controller connected, so I concluded that the game cannot play any audio through the DS4 audio device, I hope this was clear to understand, and thank you very much.

**Comment by Jvolt7** [comment]
![capturar](https://user-images.githubusercontent.com/30818823/43692868-416c83f4-9901-11e8-8134-37047f3daca7.JPG)

**Comment by Jvolt7** [comment]
![image](https://user-images.githubusercontent.com/30818823/43692975-d815bf46-9901-11e8-8f65-9b1fe1dbd219.png)
Now I set the pc audio device as the main and its works

**Comment by Jvolt7** [comment]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2260953/MGS2_VFix_debug.txt)
I will also attach the debug file, forgot about that

**Comment by VFansss** [comment]
Hi!

Yeah, I feared that this moment would come!

The game (because is programmed really...bad) require to have inside the mgs2.ini file the name on the VGA and the Sound Adapter where it have to "flush" the relative output for these two things.

My fix recognize the VGA you want to utilize, and apply the relative fix inside the file, and this is ok.

It doesn't do the same things about the Sound Adapter, because 99,999% of the time you want to use the "Primary Audio Driver" to listen your audio, so by default the fix choose it for the game to output the audio. This works even if you select other kinds of audio output (like external usb audio card).

Hidden in the 'Others' section of the Fix there is an hidden "audio peripheral" selector that let you choose the right audio output, but I've hidden it because no one has ever changed it from the default one. Also, I didn't truly finished programming it because that. 😄 

So ( **tl;dr** ) your is one of the few cases that you HAVE to change it to something else.

The sad things is that I don't have a DualShock 4 (no one I know has one, so I can't even borrow it from anyone) so I'm not 99% sure on how to solve this, but is absolutely fixable.

Is hard to make an hotfix on this just for you, because I can't find (online, neither from your screenshot) what sound adapter should I "teach" to the game to utilize.

If you have definitively set up your game (graphics, resolution and other things) you could try to send me your mgs2.ini (you can find it inside the game folder) and I can try to improvise some solutions to solve the issue.

Unfortunately, until I can put my hand on a DS4 I can't 100% guarantee on how to solve that, neither implement a fix inside...the Fix!

> I will also attach the debug file, forgot about that

Also, I should update the guide to better explain another things: please open the fix, **then press SAVE**, then exit and send me again the debug file, so I could read your internal config and some other useful things about!

I should truly explain that in the wiki; when I have time I will update it

**Comment by VFansss** [comment]
After almost 3 years I can't find a way to replicate this.

From what I know, the DS4 audio jack can't be used on PC. Truly didn't understand how all of this is possible.

Can someone guide me?

**Comment by Jvolt7** [comment]
Hello Vfansss, sorry for not replying for so long! And Yes we can use the DS4 audio jack on the PC but only when you connect it via USB, when you do that the DS4 is detected as a joystick and a audio device, as I have shown before, I had to set the PC audio device as default before starting MGS2 so it won't crash

**Comment by VFansss** [comment]
> And Yes we can use the DS4 audio jack on the PC but only when you connect it via USB, when you do that the DS4 is detected as a joystick and a audio device,

I swear that I've tried this tons of times...

Even now, if I plug my my controller in USB and I plug any audio jack into it...nothing happen :/

> I had to set the PC audio device as default before starting MGS2

😮 

I will pin this issue so everyone could sort it out in the future.

Thanks for answering!

**Comment by Jvolt7** [comment]
Try installing DS4windows and following it's instructions https://github.com/Ryochan7/DS4Windows/releases

**Comment by VFansss** [comment]
The fact is that I'm actually using DS4Windows by Ryochan!

Paradoxically, I thought installing it might conflict with the USB audio.

I'm usually using the DS4 in Wireless mode but like I sayed plugging it in USB and plugging an audio jack does absolutely nothing.

I basically give up to make it working 😛

**Comment by Jvolt7** [comment]
you must pair the controller with your pc Through USB, don't pair with bluetooth and then connect the USB, also, see if the controllers appears as a audio device in the system tray, if yes, select it and then open the game 
![image](https://user-images.githubusercontent.com/30818823/90784815-0ac94f80-e2d8-11ea-8a9c-98ae781f1ed4.png)

**Comment by Jvolt7** [comment]
Sorry I just meant to connect the controllers through USB, see if the controller is listed on the joystick configurations on control panel

**Comment by v00d00m4n** [comment]
For those who dont know - you can use audio jack via wireless connection, but only if you use DS4 with official Sony wireless adapter, which is hard to find in stores nowadays and which was part of Playstation Now package for pc.

For some stupid reason DS4 does not expose audio features to regular bluetooth adapters, just like Xbox One controller which also does not provide audio device with regular bluetooth dongles even aptX LL.
