### ISSUE TITLE
Non-Steam Game with Steam Overlay 

### ISSUE THREAD

**Issue by mcrmarcelo** [VFansss/mgs2-v-s-fix#49]
Hi there,

Do you know how I can start with Steam Overlay for chat and screenshots?

Thanks 👍 

Please, Delete this question, if this works and I made a mistake !

**Comment by VFansss** [comment]
Yup, isn't too hard.

Because game is old it need Admin rights to be played.

Steam ( by default) doesn't, so it can't "attach" steam overlay.

The only solution I found (at least until I find a better solution) is to start steam with admn rights.

Just right click on the Steam executable (or the Steam shortcut on your desktop, if you have it) and choose "Start with admin rights".

Steam will display a warning message, but you can skip it and check "Don't display this again".

The simply add "mgs2_sse.exe" ad a "Non-Steam Game" and you're done! The overlay will be attached like every other game.

If you want, put to 'OFF' the 'Open V's Fix after playing' from the 'Other' tab inside the fix settings, so when you exit the game it will automatically return to steam without opening the fix again.

Tell me if all is working good!

**Comment by mcrmarcelo** [comment]
I did that your said, and works very well.
I was think is about this configuration for "mgs2_sse.exe" forced to run in Windows XP SP3 .. and the Steam doesn't work very well with XP version.
Also we can configure the Steam folder for start with " Run this progran as administrator "  but always he asks for confirme to start :)
But they recomend don't use  https://support.steampowered.com/kb_article.php?ref=7153-AHJV-4256&l=english

Thanks a lot for now :)

**Comment by VFansss** [comment]
Ok: in fact I've found a way to make it perfectly compatible with Steam, but it need some changes to the core.

Maybe in the next version I could make it much more compatible with Steam with just few clicks...

Until then, I don't have a pretty good and fast solution 😀

**Comment by VFansss** [comment]
The new coming 1.7 version of the fix doesn't require anymore admin rights, neither compatibility flags.

This will make the Steam Overlay perfectly working, if you add the game to Steam.

Also, the SMAA filter has some certified bugs with the Steam Overlay ( [here's an example](https://steamcommunity.com/app/21090/discussions/0/828925849476590427/) ) so I've added an anti-aliasing filter trigger to the '**Graphics**' tab, so you can choose between SMAA and FXAA (that is a good filter, overall), and a little helper message to explain that directly from the fix.

Dulcis in fundo, I've also added the '**Add game on Steam**' button on the '**Extra**' tab. It was a nightmare to work on it, but now is there so who cares 😄
