### ISSUE TITLE
No shadows and green sea water

### ISSUE THREAD

**Issue by WaT30** [VFansss/mgs2-v-s-fix#50]
As the title says, there's no shadows in my game and the sea water is green. 
My settings are Model Quality on Medium, everything else on High and ON. Putting the Model Quality on High gives me really weird textures, for examples during codec calls I can only see the glasses on Otacon.

I'm playing on Acer Nitro 5 laptop with nVidia MX150 GPU.

Also I'd like to add, I'm using a PS4 controller, and every game I'm playing with the DS4 app is on. However with MGS2, it seems that with it on, it conflicts with the V fix controller setup. For example, while pressing O button, it crouches, instead of punching. I "fixed" it by not turning on the DS4 app, however without it there's no vibrations. I'll try to fiddle around the settings a bit more, might find a solution to it.

And thanks for the patch, I remember years ago when I played it on my desktop PC, it was such a fucking hassle with all of the patches, exes and what not.

**Comment by VFansss** [comment]
Lets divide the two issues:

> As the title says, there's no shadows in my game and the sea water is green.

Ok, but as you tell this phrase:

> Putting the Model Quality on High gives me really weird textures, for examples during codec calls I can only see the glasses on Otacon.

The no shadow and sea bug happen only when you put 'Model Quality' to high, or even if you put 'Model Quality' to Normal?

What GPU you see from the 'Resolution tab'? ( [The 6 on this image](https://github.com/VFansss/mgs2-v-s-fix/wiki/Settings-Menu#resolution-tab) )

Can you please read [how to activate the debug mode](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#debug-mode) and send me the 2 files written there? (You can attach them to this GitHub Issue!)

> 

[Please read this chapter on the Wiki regard DualShock4](https://github.com/VFansss/mgs2-v-s-fix/wiki/Controllers-&-Actions#original-ps4-controller)

**Comment by VFansss** [comment]
> For the GPU it says Intel UHD Graphics 620 and NVIDIA Geforce MX150 (I'm using the MX150).

Remember (like the message at the first startup sayed) that if you select a dedicated GPU (Like the MX150)  you have to MANUALLY go inside your Graphics control panel (in your case it is the NVidia one) and bind the game executable (mgs2_sse.exe) to your dedicated GPU.

Probably you didn't done that, so check it out.

Otherwise, you could select the UHD Graphics 620 and it should work...

> I managed to get the controller working properly with DS4, it turns out I just had to do this part.
" If it seems that the game is receiving "double inputs" (you press a button but the game does the action 2 times, or it lags considerably), open DS4Windows, go to 'SETTINGS' and enable 'Hide DS4 Controller'."

You could also choose to let DS4Windows open while playing and select the 'Xbox' gamepad from the Fix.
That would also re-enable the vibrations, but you have to maintain opened DS4Windows in background. 

Your choice.

**Comment by WaT30** [comment]
I did that thing for my GPU in my settings, and it worked! The shadows are back on, and the water is fine.

I also selected previously the Xbox option, I just didn't in the first place enabled the Hide option.

Thanks again!

**Comment by VFansss** [comment]
I'm happy that everything is working good 😄 

Probably I have to write better some important detail directly on the fix itself. I will consider it for the next release!

Happy playing ❗️
