### ISSUE TITLE
Hold/Toggle First Person view

### ISSUE THREAD

**Issue by lilFatkid** [VFansss/mgs2-v-s-fix#7]
Hey, great work on the fix it's very impressive. 
I want to know if there's a way to make it so you can hold the first person view button down and let go to exit. like in the console versions as apposed to toggling it on and off. I seem to remember being able to do this on the normal pc version with out this fix and I tried finding a way to do this but found nothing, only managing to customize the controls. 

Thanks in advance.

**Comment by VFansss** [comment]
Yes,it's possible. In the original PS2 game it's possible to do it holding R1 button.

The problem is that the PC version has the original xbox layout button, so it's kinda hard to conciliate pistol/rifle hold up without firing and katana moves and and at the same time mantaining all these action inside a gamepad that didn't have the "sentitive pressing button" like the PS2 controller.

So if in the PS2 version you can "hold up" guard pressing slightly the square button (1 button in total), in all the other version you have to bind these action to 3 different buttons (in my case L1,R1 and left strick button). 

I've scratched my mind for days figuring out the layout you can find in my fix. It's the only that allow ALL original action without conflicts. It's possible to change it but unavoidably can present some kind of problems/conflicts.

I can try to find another solution but I don't guarantee that it will be 100% perfect :)

**Comment by lilFatkid** [comment]
Yeah this is just what I wanted and it's working fine, thanks it's much appreciated. I think this would be a  good addition to the launcher.
