### ISSUE TITLE
"V's Fix isn't in the correct place" error

### ISSUE THREAD

**Issue by persekarvaharja** [VFansss/mgs2-v-s-fix#73]
it's in the right folder
![image](https://user-images.githubusercontent.com/46654503/51089149-173b0d00-1771-11e9-8cc2-aa5970992515.png)

**Comment by VFansss** [comment]
The fix is right: he can't find the main game executable (**mgs2_sse.exe**) and is refusing to start. I can see from your last screenshot that is behaving correctly.

Also, I can see that the folder has already a lot of fixes already applied (including the patched mgs2_sse.exe executable file) so at least you have started the fix before or...someone has done it in the past.

Please apply everything from a clean situation again, possibly reinstalling the game.

**Comment by persekarvaharja** [comment]
Will I be able to copy my save files if I do?

**Comment by VFansss** [comment]
The save files are inside the "savedata" folder that you can find upside the "bin" folder. Just cut it somewhere else, reinstall the game and copy it back.

Also, be sure that OneDrive isn't deleting .exe files because it find them dangerous. Please reinstall the game on another normal folder.

**Comment by persekarvaharja** [comment]
i don't have a savedata folder. saves have worked normally regardless. what's their file extension?

**Comment by VFansss** [comment]
Check the "My Games" folder inside "My Documents": the 1.7 version of the fix make the game read/write savegames from that folder.

![immagine](https://user-images.githubusercontent.com/15073502/51089354-118ef880-176c-11e9-89de-6d04dcc88aa6.png)


The old version simply has the same structure (folders named with "Games Data") inside the "savedata" folder mentioned above.

**Comment by persekarvaharja** [comment]
Works now, thanks.
