### ISSUE TITLE
Confused about greenscreen fix and controll questions

### ISSUE THREAD

**Issue by CiaranZagami** [VFansss/mgs2-v-s-fix#75]
I'm a little confused by two things.
1: the tanker commandant speech video glitch is a known one and a fix IS listed I just don't understand the fix, do I need to run the game on a certain version of XP? or XP and a certain version of the patch? OR just a certain version of the patch?

and 2: Is there no way to rebind keyboard controls?

**Comment by VFansss** [comment]
Hi!

Let's answer by points:

> the tanker commandant speech video glitch is a known one and a fix IS listed I just don't understand the fix, do I need to run the game on a certain version of XP? or XP and a certain version of the patch? OR just a certain version of the patch?

Just use the 1.7 version of the fix on any Windows OS you like (NB: Windows XP is actually unsupported by the fix, so in reality you must choose Windows Vista or above). The 1.7 Patch install the fix for the green screen automatically when you press 'SAVE' from the 'SETTINGS' menu of the V's fix, so everything is pretty much transparent to the users.

I will make it more clear on the [Known Bugs page](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#known-bugs), thanks!

> Is there no way to rebind keyboard controls?

Actually no, and I don't plan to make a keyboard setupper right now: is too much time consuming, pretty boring to do and I think that only few people would use it instead of gamepads.

If you are planning to use it at all costs, you can check an enhanced configuration done by an user, and you can find it [HERE](https://github.com/VFansss/mgs2-v-s-fix/issues/71)

Just download the kb.zip and unpack it inside the 'bin' game folder.

If you have any questions just ask, I will answer with very pleasure 😄

**Comment by CiaranZagami** [comment]
I tried the new keyboard setup and it works okay, but I still can't seem to control the camera/rightstick. Without that I fear the final boss will be impossible. (since your forced to use the sword and some idiot decided it should be controlled by the right analog stick)

And how do I downgrade my patch to version 1.7?

**Comment by VFansss** [comment]
> I tried the new keyboard setup and it works okay, but I still can't seem to control the camera/rightstick. Without that I fear the final boss will be impossible. (since your forced to use the sword and some idiot decided it should be controlled by the right analog stick)

I'm pretty sure the game can be finished with keyboard. Can't try it myself right now, though...

> And how do I upgrade my patch to version 1.7 the official link gives me version 1.6

In fact, a lot of people download 1.7 even if I say that is a pre-release and the 1.6 is preferred.

You can find the 1.7 version [HERE](https://github.com/VFansss/mgs2-v-s-fix/releases).

Is a pre-release though, and has some very minor bugs. I have to make a little bugfix and release the 1.7.1, but I don't have time right now...

You can try it if you are brave 😄

**Comment by VFansss** [comment]
I've edited the wiki, and now it should be much more clear on how the greenscreen bug has been fixed and where.
