### ISSUE TITLE
dinput issue

### ISSUE THREAD

**Issue by v0idp** [VFansss/mgs2-v-s-fix#76]
Is there any possibility to add native dinput support and just be able to custom assign the keys ? I can't use my Pro Controller which is beeing natively recogniced by my Windows Machine as a dinput controller but for whatever reason I can't properly use it with your fix. the only thing which "half worked" for me was when I set it to xbox layout, most buttons worked except for LB, LT, RB, RT, they were switched with the analog stick buttons for whatever reason. Tried using XOutput but doing so results in the keys beeing double triggered with my correct layout + the ones set by the xbox layout.

**Comment by VFansss** [comment]
Hi!

Sorry for the late reply!

The topic is kinda complicated.

> Is there any possibility to add native dinput support and just be able to custom assign the keys ?

Ok, the quick answer is: yes, is possible (using the old game setupper) but I will probably never make it directly possible from the V's. Doing that will require a LOT (a **LOT**) hours of work, and it will not resolve the major hassle: wasting time configuring everything and be sure that every action is correctly bound and feasible with the gamepad, especially because most of the actions and buttons aren't exactly transparent on what they do.

Designing the 2 layout available (V's and PS2 ones) wasn't easy, and the tradeoff was that only Xinput gamepads and controllers that can emulate them are directly supported. If you considerate these 2 categories, you get the 99,9% controllers used today, so it was a good deal after all.

> I can't use my Pro Controller which is beeing natively recogniced by my Windows Machine as a dinput controller

The fast way to solve this is make sure that Pro Controller is recognized as a native Xinput controller.

Have you tried to use [WiinUPro](http://www.wiinupro.com/news/wiinupro09opensource)

**Comment by v0idp** [comment]
Actually I tried using the old setup but it didn't work 100%. But after many tries I managed to get a half decent controller setting to work fine with the old setup. Also I tried using an xbox controller emulator and setup my controller for it. it was recognised as a xbox controller but when beeing ingame all my btn strokes were registered twice which was weird.

I mean the game itself does support dinput and dinput is also very good supported by windows itself. why not just make a "manual layout" where you can just set up your own layout like in the old setup ? why trade in dinput for xinput in the first place ?

**Comment by VFansss** [comment]
> I mean the game itself does support dinput and dinput is also very good supported by windows itself. Why trade in dinput for xinput in the first place ?

These two assumption are true, but the main reason is another:

every gamepad has a different button number layout, making me IMPOSSIBLE to automatically  configure the 'Start button' (for example) to the button 7, because actually the button number 7 is START on a xbox360 gamepad, but is R1 on a ps4 Dualshock and something even different on another kind of gamepad.

A xinput compliant controller (or an emulator that can bind right button to right xinput gamepad) make me possible to be 100% to what button perform what action, especially when ingame action themself are a TOTAL MESS and I have to be sure that more weird actions (like SLOW and WEAK) are bound to the same button number and things like that.

Also, the emulator software handle automatically the vibration driver (aka: is the driver and the controller is compliant, the vibrations is perfectly working like in the native game), and dinput has true issue with triggers, making them impossible to bound to the game.

Xinput is the way.

> why not just make a "manual layout" where you can just set up your own layout like in the old setup ? 

Because two main reasons:

* The high amount of useless keys like AIM,SLOW,WEAK and others that much be configured is a particular way just only to correctly perform ingame actions. 

* Like a said before, it would require a LOT (a **LOT**) hours of work. This is far out my patience limit.

> Also I tried using an xbox controller emulator and setup my controller for it. it was recognised as a xbox controller but when beeing ingame all my btn strokes were registered twice which was weird.

What xbox controller emulator? Have your tried WiinUPro like a said before?

>controller but when beeing ingame all my btn strokes were registered twice which was weird.

This is a known "issue", and isn't an issue at all, because the game (like a said before) recognize input from both drivers (xinput and dinput) at the same time.

The solution is to hide the dinput controller, or disable its input reading from your emulator. 

For example, read this paragraph that talk about the [Dualshock4 controller](https://github.com/VFansss/mgs2-v-s-fix/wiki/Controllers-&-Actions#use-ds4-with-ds4windows-instead).

I don't have myself a dinput controller, so I can't mess with that trying to find a solution. I will do as soon as I can.

**Comment by VFansss** [comment]
Ok, this is far from a real solution but I've decided to spend some time on it.

Everything that can be done to configure correctly every Dinput gamepad will be written on the [related Wiki page](https://github.com/VFansss/mgs2-v-s-fix/wiki/Appendix).
