### ISSUE TITLE
savegameCantBeMoved Error

### ISSUE THREAD

**Issue by JoesGuy** [VFansss/mgs2-v-s-fix#78]
Despite having admin rights and installing to another drive, I keep getting an error in options before it closes. Here's the debug, if it proves helpful:

02.20.50.518 -> [!][!][!][!][!][!][!][!][!][!][!][!]
02.20.50.519 -> [!]
02.20.50.519 -> [!] Fix started at 19/02/2019 3:20:50 AM (UCT)
02.20.50.519 -> [!] Fix internal version: 190104
02.20.50.520 -> [!] V's Fix has admin rights
02.20.50.520 -> [RETRIEVE LAST.LOG] last.log found in ApplicationFolder
02.20.50.520 -> [PRINT LAST.LOG] A last.log file exist. Reading it...
02.20.50.521 -> [PRINT LAST.LOG] Log Name:C:\Users\I5\AppData\Local\Temp\log9B17.tmp
[ FS_PATH_CTGR_INI ]: G:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance\bin/.
[ FS_PATH_CTGR_STAGE ]: G:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance\bin/../cdrom.img
[ FS_PATH_CTGR_STREAM ]: G:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance\bin/../cdrom.img
/*-- Graphics System Daemon Start --*/
Selected Device:NVIDIA GeForce GT 440
Device[0]:NVIDIA GeForce GT 440 
Can't Find Device:NVIDIA GeForce GT 440
Video Device:
	Driver         :nvd3dum.dll
	Description    :NVIDIA GeForce GT 440 
	Driver Version :00080011000D008E
	VendorId       :000010DE
	DeviceId       :00000DE0
	SubSysId       :23081462
	Revision       :000000A1
Create Device:
	DeviceType     :1
	BehaviorFlags  :00000054
	Windowed       :0
	FullScreen_RefreshRateInHz :0
	FullScreen_PresentationInterval :1
	BackBuffer     :( 640, 480)
	MultiSampleType:0
	SwapEffect     :1
	BackBufferFormat:22
	BackBufferCount:2
	EnableAutoDepthStencil:1
	Flags          :00000001
DG_AdjustConfig:RADEON
BackBufferFormat:
	Format     :21
	Size       :(512, 512)
	RendSize   :(512, 480)
	DepthFormat:75
Shadow:
	Format     :21
	Size       :(256, 256)
	DepthFormat:80
/*-- CheckUsableTextureFormats --*/
	Format 20 --> 22
	Format 27 --> 23
	Format 29 --> 26
	Format 30 --> 23
	Format 40 --> 26
	Format 41 --> 23
	Format 52 --> 23
	Format 61 --> 23
	Format 65 --> 23
	Format 67 --> 23
	Format 1498831189 --> 23
X2W_ErrorPrintfID:ID 8
Ending game.
Data not saved will disappear.
OK?

02.20.50.526 -> [+] Configuration_file.ini seem missing some key. Need to autoconfig!
02.20.50.527 -> [!] forbidStart is false. Starting winform
02.20.50.610 -> [FATALERROR CHECKING] Checking for fatal errors...
02.20.50.610 -> [RETRIEVE LAST.LOG] last.log found in ApplicationFolder
02.20.50.611 -> [FATALERROR CHECKING] Check has returned this code: WrongVideoAdapter
02.20.52.933 -> [!] Showed a messagebox with code: fatalError_WrongVideoAdapter
02.20.52.933 -> [+] Form1 constructor has done. Waiting user input.
02.20.54.935 -> [+] Start game button pressed

**Comment by VFansss** [comment]
Hi!

Please do this actions in the precise order I write them:

* Open the V's Fix
* Press 'SETTINGS'
* Press 'SAVE'
* Send me the new debug log you find on your desktop

**Comment by JoesGuy** [comment]
I cannot hit save, as the popup prevents me from doing anything and closing that closes the program.

**Comment by VFansss** [comment]
Ok, don't worry. Just let the fix close and send me the debug log.

**Comment by JoesGuy** [comment]
Sure thing.
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2879162/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
I'm pretty sure that the popup that show up this time it telling itself what you could do to solve the issue, but I think that you get stuck in an infamous bug there is in the 1.7 version of the fix I have yet to correct (That's why the 1.7 version is flagged as a pre-release and not a definitive version, and the Wiki download link point to 1.6)

To be perfectly sure please download and use the [1.6 version of the fix](https://github.com/VFansss/mgs2-v-s-fix/releases/download/v1.6/MGS.V.s.Fix.v1.6.zip), and if it has other issues please send me again the debug log.

**Comment by JoesGuy** [comment]
1.6 works just fine. But the pop-up isn't telling me to download folders. Just to "start using admin rights" which I already have. :(

**Comment by VFansss** [comment]
> 1.6 works just fine.

Sorry for the silly question, but the 1.6 is working good and this...

> But the pop-up isn't telling me to download folders. Just to "start using admin rights" which I already have. :(

is referring to the 1.7, am I right?

**Comment by JoesGuy** [comment]
That's correct.

**Comment by VFansss** [comment]
Is strange, because the only popup that the debug file told me that has been show up if the "savegameCantBeMoved" popup, that is this message:

![immagine](https://user-images.githubusercontent.com/15073502/53007051-c5079e80-3436-11e9-92b2-f09fb276ed47.png)

And that prompt a manual action, and doesn't require admin rights.

Just the last question: from where you have downloaded the 1.7 version? Because every direct link I made point to 1.6, so what links have your followed to download the 1.7?

**Comment by JoesGuy** [comment]
I downloaded it from the releases section right here.

**Comment by VFansss** [comment]
The problem should be solved in the last 1.7.1 build.
