### ISSUE TITLE
Can't extract exe zip at first startup

### ISSUE THREAD

**Issue by Wyniest** [VFansss/mgs2-v-s-fix#79]
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/2897394/MGS2_VFix_debug.txt)
 
11.35.13.061 -> [!][!][!][!][!][!][!][!][!][!][!][!]
11.35.13.077 -> [!]
11.35.13.077 -> [!] Fix started at 23/02/2019 23:35:13 (UCT)
11.35.13.092 -> [ ] Fixed exe not applied. Applying it
11.35.13.108 -> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance\bin\mgs2_sse.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at mgs2_v_s_fix.Unzip.UnZippa(String fileToUnzip, Boolean OverWrite)
   at mgs2_v_s_fix.Program.Main(String[] args)
11.35.14.207 -> [!] Showed a messagebox with code: debug_mode
11.35.33.721 -> [!] Showed a messagebox with code: initiating_error
11.35.33.721 -> [!] forbidStart is true. Closing.

**Comment by VFansss** [comment]
This is a situation that has been reported from other users, and I yet have to understand what is the cause.

The issue is that something is blocking the V's Fix from extracting the fixed game executable from the zip embedded in the fix.

The solution is: do it manually.

* Download the fixed exe zip from [HERE](https://github.com/VFansss/mgs2-v-s-fix/raw/master/mgs2%20v's%20fix/Resources/3_fixed_exe.zip)

* Open the zip, extract the content inside the 'bin' game folder
    * In your case the folder is here: C:\Program Files (x86)\KONAMI\MetalGearSolid2 Substance\bin\

* Create a file called "_fixed_exe_applied.sss" (without quotes) inside the bin folder. Is not important what content it have: the only important things is that a file there called this way.

* Open the V's Fix and go ahead.

The V's Fix require admin right, so I don't understand what it blocking it from overwriting the .exe.

Did you have any antivirus running on your PC?

**Comment by Wyniest** [comment]
Thanks for getting back to me so soon!
I had:
- Turned off UAC.
- Turned off "Windows Firewall".
- Disabled my Antivirus Software.
- Given all Rights and Permissions to the .exe File. 
- Rebooted the system with all of the above in place. 

Unfortunately, nothing I tried seemed to make any difference to, A: The Error message, B: The .exe file's actions. 

Many thanks.

**Comment by Wyniest** [comment]
So I did the above fix, it worked perfectly! Thank you very much for your speedy response and simple solution!

**Comment by VFansss** [comment]
I'm glad it worked 😄 

I didn't identified why users get this rare bug. I've pretty sure that the unzipping function is working good, and I'm also sure that the .exe is not used by the fix. I will keep an eye on it.

I'm releasing a new version of the fix in seconds, so keep an eye on it if you want 👍 

Have fun and happy Sunday ❗️
