### ISSUE TITLE
Game closes after the first 2 screens, or goes blackscreen

### ISSUE THREAD

**Issue by lDan89l** [VFansss/mgs2-v-s-fix#85]
Ciao!

First of all, thank you for your precious work! I downloaded the game and installed it without applying any patch/fix, as recommended.

I am having the following issue: after I start the game (from the menu of MGS2SSetup file) I just see the first 2 screens of the game (the 1st with the logo of Konami and the 2nd with "Konami Computer Entertainement Japan"). After that, the program just closes without any error displayed.

If I try to start the game from the file mgs2_sse, it goes a little further: I see blackscreen while the music keeps going in the background.

My OS is Windows 10 64bit. You find attached the debug file. Can you please help me? :)

[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3143779/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
Hi!

> After that, the program just closes without any error displayed.

This is a very strange error. and unfortunately I'm not 100% on how to solve it because, even from the log, everything seems ok.

Please try to re-install the game to another location and try to apply the [1.6 Version](https://github.com/VFansss/mgs2-v-s-fix/releases/download/v1.6/MGS.V.s.Fix.v1.6.zip) of the fix.

Maybe something else will show up to point me to the right solution...

**Comment by lDan89l** [comment]
> You can try to delete 'Configuration_file.ini', then open the fix, press setup and apply the default configuration and check if it works...

I did this and it when I start the game it shows a new error (you can see it attached).

![Cattura](https://user-images.githubusercontent.com/50252870/57180420-966f6080-6e88-11e9-9db7-f5a6e4500de1.JPG)
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3144459/MGS2_VFix_debug.txt)

**Comment by lDan89l** [comment]
I tried to reinstall it and it's now solved :)
