### ISSUE TITLE
Nintendo Switch Pro Controller and x360ce

### ISSUE THREAD

**Issue by WilliamArtean** [VFansss/mgs2-v-s-fix#86]
First I want to say well done ; this patch allows me to play the game on my laptop without any compatibility or graphical issues, I imagine it wasn't an easy task !

Now, I have a controller issue : I'm trying to play the game with a Nintendo Switch Pro Controller (it's the only gamepad I have, sorry) x360ce uses to emulate a Xbox controller. I have selected 'Xbox' in the 'Controller' tab.
Usually, x360ce emulates the pad without problems, but here it doesn't accept my gamepad as a valid configuration (I have a red square in the 'Controller 1' tab).

I may seem like an issue with x360ce only, but I think I know what the cause of the problem is : 
x360ce uses a XInput1_3.dll file, which already exists in MGS2 game folder (I assume it is used by the patch). I have no problem emulating a Xbox controller when x360ce has to create this file from scratch, but here it seems that whatever is it that's already in it is causing this problem.

I have no idea how XInput1_3.dll works, but after searching on several forums, I thinks it's possible an input profile with the same name as the one used by x360ce with my controller exists in the .dll, and since it isn't made to work with a Switch Pro Controller, it doesn't recognize my controller. Since the controller is named "Wireless Gamepad" in x360ce, it's possible that a profile by that name already exists, it's not a very imaginative name after all.

I can upload some files if you need them to know exactly what's causing this problem. I apologize if my english is a little flawed, ask me to reexplain if some points are nor clear enough.

**Comment by VFansss** [comment]
Have you tried [WiinUPro](http://www.wiinupro.com/)?

**Comment by WilliamArtean** [comment]
Okay so, I tried WiinUPro ; it took me a while to understand how it works, and even longer to install the SCP Drivers needed (which by the way caused my touchpad to stop working, but well ^^).

It partly fixes the problem though. Now I do have a fully functional emulated Xbox controller, and it works in the game. BUT the game also detects another input from that same controller ! X( So some of my inputs are detected twice by the game, and the others are a mess, because that second "unwanted" controller has really weird mapping. Fisrt person is now on start, inventory and weapons are on L3 and R3, and start and back are now on the triggers (meaning I pause the game when I press the right trigger on my gamepad). Really weird, and not at all comfortable to play.

The problem now is to eliminate this unwanted controller. The thing is it's there even when I'm not using any virtual controller emulator (no WiinUPro, no x360ce). So, it may be because the patch directly takes input from it (or maybe the game itself, I don't know how the patch works regarding controllers). Maybe you need a debug log file to see things more clearly ?

**Comment by VFansss** [comment]
Before all: I'm truly sorry for the VERY late reply.

I was sick these days, and then I forgot to reply 😢 

> which by the way caused my touchpad to stop working, but well ^^).

😭 

> It partly fixes the problem though. Now I do have a fully functional emulated Xbox controller, and it works in the game. BUT the game also detects another input from that same controller !

This unfortunately is a known issue.

> because that second "unwanted" controller has really weird mapping.

Paradoxically, that "unwanted" controller is the Switch Pro controller.

The emulated xbox xinput controller has the right button layout, but at the same time the pro controller is working and is pressing another keystroke, also with a different button number.

So you get 2 input: one from the xbox controller (and is doing the right action), and another from the switch controller (with a different button layout order, that does a totally different action). 

> The problem now is to eliminate this unwanted controller.

The perfect working solution is make the software/driver you use to "hide" the old controller, and just let the "translated xinput" controller work.

Is a things that I've mentioned for the [DualShock4 on the Wiki](https://github.com/VFansss/mgs2-v-s-fix/wiki/Controllers-&-Actions#use-ds4-with-ds4windows-instead), because DS4Windows has this possibility.

I don't know if WiinUPro has a similar option available. [I guess not](http://wiinupro.boards.net/thread/29/block-dinput-games)

Another way would be to do a personalized button layout just for the Switch Pro Controller, but this probably will not solve two other issues:

* Vibration will not work
* Trigger will not be recognized (because they aren't actually button, but axis. And the game doesn't recognize axis as things boundable to actions)

I unfortunately don't know a better solution: is a "things" that afflict a lot of other people, but I don't have a non-xinput controller (Every one I have only works under xinput), so I should find an old dinput controller or another peripheral that is recognized as a dinput controller and try to figure it out.

**Comment by WilliamArtean** [comment]
> I'm truly sorry for the VERY late reply.

Don"t worry. I hope you are back in shape :)

Since WiinUPro can't hide the Pro Controller, I guess I'm a bit stuck now. I think it will be easier to switch to the good old mouse & keyboard (I see there are a couple of layouts available in the wiki, that's great). Bye bye controller, see you in MGS3. :D

Anyway, thank you very much for having taken the time to look into my issue. Even if there is no perfect solution to be found, I appreciate it a lot. 😃

**Comment by VFansss** [comment]
Ok: I think I've found a solution for this annoying bug. 

It require XOutput (fantastic software, by the way) and HidGuardian. 

Unfortunately, isn't something I can include inside the fix, and require 5 minute of fiddling around...

As soon as I can, I will write a comprehensive guide, and I will include it on the Wiki per everyone.

**Comment by VFansss** [comment]
Well, is fantastic to see that almost a year later I didn't found the time to write that fucking tutorial.

I've also seen that Hidguardian driver gone offline, thus I don't 100% sure that is a good path to follow.

The next fix version will have some keyboard layout pre-configured.

Regardind the Dinput controller, I've made [a page on the wiki](https://github.com/VFansss/mgs2-v-s-fix/wiki/Appendix#use-a-dinput-controller).

Hope that this time I will find the force to sort something out...
