### ISSUE TITLE
Swapping Rumble Motors?

### ISSUE THREAD

**Issue by TehNewbie** [VFansss/mgs2-v-s-fix#89]
Hello there! MGS2 plays perfectly for me, thanks to your fix. I ran into a small quirk, though. I'm using a DualShock 3 with SCP, and rumble works for me, but only the fast motor. I think that it should be the "heavier" one that should be on. I'm not sure if it's something you can fix, but I would definitely appreciate some advice. :smile:

**Comment by VFansss** [comment]
Hey there!

I'm not so used to the controller vibration, because I'm currently using a PS3 sixaxis.

I will try some other controller to check if is a general issue or is something related to SCP/DS3 😄

**Comment by TehNewbie** [comment]
That would be amazing, thank you so much!

**Comment by VFansss** [comment]
Wow😲 

I didn't tested this yet because I have to get some other gamepad to check if is a general issue, something related to XInput Plus or something related to the DualShock3, but I'm glad you figured something out for yourself!

>  I ran MGS2. The rumble was working (both motors), but the triggers were still malfunctioning.

Yup, because XInput plus allow me to bind triggers to buttons, and it restore vibrations. Deactivating it will deactivate both things, off course...

> After a bit of digging, I found a Dinput Wrapper for SCP Driver

Can you please tell me what it is?

It would be very cool to know it: maybe I can figure how to add it to the fix, or at least add it to the wiki.

**Comment by TehNewbie** [comment]
Sure thing! It's this one:
https://forums.pcsx2.net/Thread-Dinput-Wrapper-for-SCP-Driver

**Comment by VFansss** [comment]
Seems that the source code of these drivers can't be find nowhere.

So they are basically useless, and we can't lower the intensity of vibrations in no way.

If I found another way/wrapper that allow me more freely configure rumbles on DS3, I will gradly try to do that 😢
