### ISSUE TITLE
Possible fix for green screen?

### ISSUE THREAD

**Issue by Tomasak** [VFansss/mgs2-v-s-fix#9]
You said few times the green screen problem in snake's campaign could be caused by directx 8 and 9 incompatibility.
So couldn't this thing fix it? https://github.com/crosire/d3d8to9

**Comment by VFansss** [comment]
Sorry for the late reply!

I've already used a dx8-to-dx9 wrapper in the project (the one from ENB series, you can check out in "Software Contribution"). It's used when you enable Anti-Aliasing (because it don't work under dx8).

Unfortunatelly isn't enough: same problem. I think is some other deep problem...

I didn't tried the one you linked (not yet) but honestly I don't think it will solve anything.

What's the funny things?

In the Hold N.2 there are 2 projector that switch back and forth the commandant image.

Now probably you know what's the easter egg present in this room but if you don't (I didn't tried it until the last time I played it some months ago!) here: you can manually switch the 2 projector pressing action button where standing near one of them.

If you keep switching them a lot it will trigger an...easter egg video.

Well: THAT VIDEO WORK PERFECTLY. 

That keeps me bugged a lot cause the projector don't work when there's a main game features but they will on a such...ehm...things :p

I contacted several people for help but for now it's an unsolved issues...

**Comment by Tomasak** [comment]
Another method could be https://fdossena.com/?p=wined3d/index.frag 
Problem is, i get crashing before konami logo appears and can't debug it. 
It helped Silent Hill 2 to fix some texture/graphics bugs.

**Comment by VFansss** [comment]
I've tried every trick I know and I got the same result.

Usually it crash before intro when it has heavy problem with render. I don't think it's compatible with MGS2 :(
