### ISSUE TITLE
Game freezes on commanders speech (Tanker chapter)

### ISSUE THREAD

**Issue by Velizar-fon-Fai** [VFansss/mgs2-v-s-fix#93]
After i survive ambush, Snake goes to another room where he speeks with Otacon about Metal Gear. But when disscusion ends , commander starts to speak and game freezes 
[MGS2_VFix_debug (2).txt](https://github.com/VFansss/mgs2-v-s-fix/files/3317285/MGS2_VFix_debug.2.txt)
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3317286/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
From the log, I can see that you have selected the "Intel Integrated Graphics" from the VGA list on the "Resolution tab" of the Fix

(here's an example) 
![immagine](https://user-images.githubusercontent.com/15073502/59972988-0cdf3380-9599-11e9-8de1-5f6d341fd4c5.png)

Select the dedicated VGA instead, because I think the game is set for running under the Nvidia VGA (Check [this chapter of the guide - point 6](https://github.com/VFansss/mgs2-v-s-fix/wiki/Settings-Menu#resolution-tab) to a better explanation of what I'm meaning.

**Comment by VFansss** [comment]
Hi!

Have you solved, or have any news regarding this?
