### ISSUE TITLE
Failed creating Direct3DDevice8 Object

### ISSUE THREAD

**Issue by betovanbuuren** [VFansss/mgs2-v-s-fix#94]
Hi,

I would like to report the issue im having when trying to launch the fix with my new laptop Dell G5 15 5590, i installed the game and before apply the fix it works good, but after i apply the 1.7.2 fix, im getting this error when opening the game, this machine has 2 gpu, the integrated one and a RTX2060 from nvidia.

On the nvidia manager i did some tests by making the default to one card the first try, and to the other on the second try (and make sure that in the settings option is the same card selected) but even that way im unable to open the game.

Attached the debug log, i hope you can help me to play this game on my laptop :).

[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3364125/MGS2_VFix_debug.txt)

**Comment by betovanbuuren** [comment]
Second log from another test
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3364133/MGS2_VFix_debug.txt)

**Comment by VFansss** [comment]
Hi there!

From the second log you posted (the right one, because I needed a log where you actually pressed the 'SETTINGS' button, [as I wrote on the Wiki page](https://github.com/VFansss/mgs2-v-s-fix/wiki/Troubleshooting-&-Debug-mode#how-to-correctly-use-it), it seems that you set a strange resolution: 1536x864.

Your laptop (nice machine, btw!) should have at least a 1920x1080 resolution monitor, so simply set up 1920x1080 in the [https://github.com/VFansss/mgs2-v-s-fix/wiki/Settings-Menu#resolution-tab](resolution tab.)

This should do the trick.

Please report back if it's working, have a nice day!

**Comment by betovanbuuren** [comment]
Thank you, let me try that today and i will report back!

**Comment by betovanbuuren** [comment]
Hi again,

I did the changes on the resolution tab, but the issue still the same, i enabled debug logs and click settings & save, several times, and on the log i can only see the one attached below
[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3364757/MGS2_VFix_debug.txt)

Do i need to do something else?

**Comment by VFansss** [comment]
You installed the game...on your desktop? :/
Can you please try to install it to another location?

Also: the last log you sent me is useless, because is not containing any settings you made. Please delete it, close the fix and do it again following the guide I've posted above!

Regarding the main issue, try these 2 solutions:
* Try to **ENABLE** anti-aliasing (you can find it on the graphical tab)
* Enable the window mode (on the resolution tab)

**Comment by betovanbuuren** [comment]
Found the issue!! In case someone has this behavior, i need to install the below packages and that did it:

1.- DirectX SDK
2.- vcredist_x64.exe

After that and with the configurations you previously told me, it works! 

Thank you for your help! have a nice weekend

**Comment by VFansss** [comment]
Good to know, my friend!

I will add this info to the Wiki when I have time!

Enjoy your brand new laptop, have a nice day and (last but not least) have fun with the game 😄

**Comment by betovanbuuren** [comment]
Thank you for develop this great fix!!

**Comment by wolfinston85** [comment]
Thanks for the fix, the resolution trick worked for me, was getting the same error but had the vcredist installed, setting the res to 1080p within the launcher worked.
