### ISSUE TITLE
Failed creating IDirectSound8 Object + Missing shadows

### ISSUE THREAD

**Issue by mr25063** [VFansss/mgs2-v-s-fix#98]
I installed a European copy of MGS2 Substance from the official disc and V's fix 1.7.2 yesterday, which worked bug-free after some tinkering to fix very minor things. I have made one save in game, and changed no settings since yesterday. Sound was working. However, now when i get past V's menu, the game outputs...

![image](https://user-images.githubusercontent.com/54743679/64064553-ee319480-cbfa-11e9-96b7-08638902ed7c.png)

...and fails to start. 

I've looked through the V's Fix github page but haven't found my exact issue. Looking up the issue on google sends me to 'fixes' from 5 years ago that don't work with Windows 10 or V's Fix.
I've also tried deleting, then updating my sound-card drivers. This didn't work. I've also tried using V's Fix 1.6, which didn't work. I've moved back to 1.7.2

The only thing I can think of is a reinstall - I have the game downloaded on my D:\ drive, which i think V has suggested may cause issues? 

I'm:
Using Windows 10 on a Dell Laptop
Using 1920 x 1080 resolution
Using Intel UHD Graphics 630 (I have a 1050Ti, but V's fix suggests i use Intel, and shadows break when using my Nvidia graphics card)
Using my default speakers, which are Realtek Audio. I have steam streaming speakers, but they are not my default device.

Here's my debug file:

[MGS2_VFix_debug.txt](https://github.com/VFansss/mgs2-v-s-fix/files/3562495/MGS2_VFix_debug.txt)

**Comment by mr25063** [comment]
OK I DID A FRESH INSTALL OF THE GAME ON MT C:\ DRIVE! ALL IS GOOD

Thank you to V for doing an amazing job of making my favourite game playable on my favourite device  :)

**Comment by VFansss** [comment]
Is a kinda strange situation. Let go in order:

> which worked bug-free after some tinkering to fix very minor things. I have made one save in game, and changed no settings since yesterday

So, you applied all correctly, played a little, than the day after it suddently doesn't work anymore?

Do I understand you correctly?

> The only thing I can think of is a reinstall - I have the game downloaded on my D:\ drive, which i think V has suggested may cause issues?

Installing the game on a different drive shoudn't cause anything strange (I've done it myself in the past, also), but now I'm not so confident on that

I don't think you would want to reinstall the game again on your D drive, but I would truly love if you do that....

> Here's my debug file

The debug file is missing your personal configuration. It would have been very useful to understand the issue.

The correctly action to perform is: open the fix -> press OPTION -> **press SAVE**

If you want to do that and send me again the file, it would be fantastic.

> Using Intel UHD Graphics 630 (I have a 1050Ti, but V's fix suggests i use Intel, and shadows break when using my Nvidia graphics card)

Well, by default the V's fix select the Intel card because...why not?

If you want to use your NVidia, just select it from the fix.

But **then** (and you can lear why from the [Wiki](https://github.com/VFansss/mgs2-v-s-fix/wiki/Settings-Menu#resolution-tab) or directly from the fix if you press the "Be sure to select the right VGA" link) you have to change your VGA preference from your VGA Driver panel.

Because you have an NVdia and a laptop (a nice one,btw!), right click on your desktop, select "NVidia driver panel", add the game executable (mgs2_sse.exe) and then select 'Nvidia  GPU' or something like that (My driver panel is in italian, sorry :p )

![immagine](https://user-images.githubusercontent.com/15073502/64065873-7a4fb600-cc13-11e9-88e5-84d8ac378cad.png)

**Comment by mr25063** [comment]
Hey! Thanks for the reply.
Just want to say that yes, I just did a fresh install on my C:\ drive (with all my OS data, Program Files etc) and the game fully works!

> So, you applied all correctly, played a little, than the day after it suddently doesn't work anymore?

Yes, that's what happened. I started my laptop the next day and the game didn't start (due to the "Failed creating IDirectSound8 Object"). V's Fix Menu worked, but after pressing 'play' I got the error.

> The debug file is missing your personal configuration. It would have been very useful to understand the issue.
> The correctly action to perform is: open the fix -> press OPTION -> press SAVE
> If you want to do that and send me again the file, it would be fantastic.

Sorry, but I no longer have the debug file :( However, I have the game (now working) configured exactly as it was when it did not work. If you want this I'd be happy to send the file - but it's probably of no use to you now.

> If you want to use your NVidia, just select it from the fix.

I had done this, but weirdly, shadows are not present if I use my NVidia (even after messing with shadow settings in the Fix menu). My Intel graphics run the game fine, and I get the same framerates etc, so I don't mind

**Comment by VFansss** [comment]
> I had done this, but weirdly, shadows are not present if I use my NVidia (even after messing with shadow settings in the Fix menu). My Intel graphics run the game fine, and I get the same framerates etc, so I don't mind

If you are on a recent Windows 10 version, you can globally select your preferred VGA directly from Windows settings menu, thus making the game easily compatible with your dedicated VGA.

You can check the guide [HERE](https://github.com/VFansss/mgs2-v-s-fix/wiki/Settings-Menu#graphical-adapter).
